### ISSUE TITLE
"Global Cores total" wrong

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#104]
Problem:
----------- 
After the last merge, the "Global Cores Total" changed to a dynamic value "Native Cores Limit"+"Foreign Cores", which is not what it should be.    
Before it was the quota obtained from the cloud, which was correct.

Solution:
----------- 
Change "Global Cores Total" back to the fixed quota for a cloud. It should be the quota obtained from the cloud itself, or the soft quota when put in. But it should not be a dynamic value.

**Comment by crlb** [comment]
group by on an integer column (slot_type, 1 or 8 core) was not differentiating the values correctly. We have found this problem to be intermittent. The workaround/fix was to "group by group_name,cloud_name,slot_tag" instead of "group by group_name,cloud_name,slot_id,slot_type" where "slot_tag" is a string concatenation of slot_id and slot_type.

**Comment by MarcusEbert** [comment]
This issue is about the column "Global Cores total", not about the Slot cores columns

**Comment by kcasteels** [comment]
We are now using the quota limit again, as opposed to native+forigen+idle.
