### ISSUE TITLE
web gui: changing group while in "Images" or "Keys" doesn't work

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#114]
go to
https://csv2.heprc.uvic.ca/images/

and change group. You are still in the old group. Same for "Keys".

**Comment by colsond** [comment]
It seems the functionality of the dropdown menu has changed to update the group on a post request, the keypair and image views were never updated to reflect this change.

This functionality looks like it was implimented in the view_utils "set_user_groups" function which checks if the request that was passed in was a post and then extracts the group from the post method.

This should be fixed by updating the keypair and image views to import this function and call it at the beginning of the request to set the user's active group to the new target.

I'll do this update after the merge today.

**Comment by colsond** [comment]
fixed as of commit b599fa8679a1974600f09afc1cbd4401e95bfd94

**Comment by rseuster** [comment]
close
