### ISSUE TITLE
timestamps in csv2 and its DB

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#154]
just to keep track of the issue

**Comment by colsond** [comment]
This should be fixed in dev as of commit df32568d7ae9429dbd44d8ae593a967cea30631b.

The problem was the boot time showing up as times from different timezones. When coming directly from openstack the time would be in UTC, but if the vm didn't yet have a start time it was given a current timestamp in localtime. The aforementioned commit converts the time from openstack to our localtime to match the database functions.

**Comment by rseuster** [comment]
fixed.
