### ISSUE TITLE
totals row missing on web gui

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#167]
just looking at the ATLAS project  on the web gui, the totals row is missing.

**Comment by kcasteels** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;} It is missing because we hacked in the new global status view into Stable 2.2 without all the new code changes from dev. This is already working on the dev branch.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: March 18, 2019 09:28To: cloudscheduler@noreply.github.comReply to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [hep-gc/cloudscheduler] totals row missing on web gui (#167)  just looking at the ATLAS project  on the web gui, the totals row is missing.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by kcasteels** [comment]
Fixed in dev, closing.
