### ISSUE TITLE
Should we have an exclude in yum.conf ?

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#207]
Like this
exclude=condor*

and run yum auto-updates ?

**Comment by MarcusEbert** [comment]
Are we sure we exclude everything that could break things in an auto-update?
What if mariadb api changes in a future version, or other things?

Instead of black listing, alternative would be a white list of packages, e.g. ca_*,  that could always be updated without problems and run yum update on those list?

**Comment by rseuster** [comment]
Indeed needs more thoughts and thinking. This issue is just a reminder to address it sometimes in future.

**Comment by rseuster** [comment]
closing.
