### ISSUE TITLE
VM image field in web interface shows only subset of all VM images on the cloud

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#214]
csv2a, belle group, cc-east cloud:

There are cernvm3 images on the account in the cloud. That can be seen in the glint tab and also when doing "glance image-list" (don't know how to see all images on the cloud using "cloudscheduler" cli)

In the cloud settings for cc-east in the "VM Image" field, no cernvm3 image is listed. It seems there is only a small subset  (25) of all images (79) shown.

**Comment by crlb** [comment]
Indeed; glint shows belle/cc-east as having cernvm3-micro-2.8-6.hdd and cernvm3-micro-3.0-6.hdd , but: 
MariaDB [csv2]> select * from cloud_images where name like '%cernvm3%';
+------------+------------+--------------------------------------+------------+------------------+-------------+-------------------------+----------+------------+----------+---------+--------------+
| group_name | cloud_name | id                                   | cloud_type | container_format | disk_format | name                    | size     | visibility | min_disk | min_ram | last_updated |
+------------+------------+--------------------------------------+------------+------------------+-------------+-------------------------+----------+------------+----------+---------+--------------+
| atlas      | arbutus    | 510ba3e4-8efc-4165-b9f0-aa3f1ccc39fd | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | shared     |        0 |       0 |   1561673886 |
| atlas      | arbutus    | 8565d53a-1e6e-4ffc-b7a7-b51bbac4bd3f | openstack  | bare             | raw         | cernvm3                 | 25231360 | private    |        0 |       0 |   1561673886 |
| atlas      | otter      | d4da7a7a-43f4-45ef-a595-a02529bee243 | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | public     |        0 |       0 |   1561673886 |
| belle      | arbutus    | 510ba3e4-8efc-4165-b9f0-aa3f1ccc39fd | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | shared     |        0 |       0 |   1561673886 |
| belle      | arbutus    | 8565d53a-1e6e-4ffc-b7a7-b51bbac4bd3f | openstack  | bare             | raw         | cernvm3                 | 25231360 | private    |        0 |       0 |   1561673886 |
| belle      | otter      | d4da7a7a-43f4-45ef-a595-a02529bee243 | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | public     |        0 |       0 |   1561673886 |
| test       | dair-ab    | c49fb576-962d-4bdc-b113-28f1e2267df4 | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | private    |        0 |       0 |   1561673886 |
| test       | dair-qc    | c49fb576-962d-4bdc-b113-28f1e2267df4 | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | private    |        0 |       0 |   1561673895 |
| testing    | dair-ab    | c49fb576-962d-4bdc-b113-28f1e2267df4 | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | private    |        0 |       0 |   1561673886 |
| testing    | dair-qc    | c49fb576-962d-4bdc-b113-28f1e2267df4 | openstack  | bare             | raw         | cernvm3-micro-3.0-6.hdd | 25231360 | private    |        0 |       0 |   1561673895 |
+------------+------------+--------------------------------------+------------+------------------+-------------+-------------------------+----------+------------+----------+---------+--------------+
10 rows in set (0.001 sec)

So could be either glint or the poller that is giving us this discrepency; which won't happen when glint uses csv2_clouds.

**Comment by MarcusEbert** [comment]
As I said, also "glance image-list" shows all images, which are the same like glint. From a user's point of view it looks like the web interface doesn't show all. If it doesn't show all because they are not in the database, then it is right that it is an internal problem of what goes into the db.   

It's not just that single image missing, while glint shows all - I only found the problem when looking for that single image. So the problem is not with glint.

**Comment by colsond** [comment]
I did this image query using the the belle cc-east credentials and it only returned the following:

<Image: cernvm4-micro-2018.10-1.hdd>
<Image: Ubuntu-16.04.5-Xenial-minimal-x64-2019-01>
<Image: Ubuntu-18.04.1-Bionic-minimal-x64-2019-01>
<Image: Ubuntu-18.04.1-Bionic-x64-2019-01>
<Image: Ubuntu-16.04.5-Xenial-x64-2019-01>
<Image: CentOS-7-x64-2018-11>
<Image: CentOS-6-x64-2018-11>
<Image: Debian-9.7.0-Stretch-2019-01>
<Image: Fedora-29-1.2-x64-2018-10>
<Image: Ubuntu-16.04-Xenial-minimal-x64-2018-07>
<Image: Ubuntu-18.04-Bionic-minimal-x64-2018-07>
<Image: Ubuntu-18.04-Bionic-x64-2018-07>
<Image: Ubuntu-16.04.4-Xenial-x64-2018-07>
<Image: CentOS-7-x64-2018-05>
<Image: CentOS-6-x64-2018-05>
<Image: Debian-9.4.7-Stretch-x64-2018-07>
<Image: Fedora-28-1.1-x64-2018-06>
<Image: cernvm4-micro-2018.06-2.hdd>
<Image: cernvm4-micro-3.0-6.hdd>
<Image: Ubuntu-18.04-Bionic-x64-2018-04>
<Image: Fedora-27-1.6-x64-2017-11>
<Image: Ubuntu-16.04.4-Xenial-x64-2018-04>
<Image: CentOS-7-x64-2018-02>
<Image: CentOS-6-x64-2018-02>
<Image: Debian-9.4.2-Stretch-x64-2018-03>

Which is what csv2 is reporting, so that much is working properly.

Perhaps the images listed in glint are in error? What credentials did you use to do the glance image list?

**Comment by MarcusEbert** [comment]
Glint is showing the correct images. For glance I use the same credentials like in the cc-east cloud for group belle.

**Comment by colsond** [comment]
So the difference between os poller and glint poller is that the glitn poller gets the images from a glance client whereas os poller uses nova. For some unknown reason the nova list is incomplete and as such we will need to switch to the glance client for images.

**Comment by MarcusEbert** [comment]
Is the change in stable-2.5?

**Comment by colsond** [comment]
Yes

**Comment by MarcusEbert** [comment]
Okay, closing.
