### ISSUE TITLE
show rabbitmq message queue depth in one of the detailed views

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#251]
dev2 has re-occuring problems with the htc-agent. Would be nice to also show the
message queue depth, we should then see when problems started and once e.g.
htc-agents are re-started, how long it takes to clear the queue.

**Comment by colsond** [comment]
This is achievable with the system command `rabbitmqctl list_queues` but may also be available via the python package. If it's easily available via python it would probably be best gathered in the machine poller where the status of the agent is determined. My initial thought was to gather this information in the status poller but that would require some addition configuration and python imports.

After some deliberation if the queue length is available via python perhaps it would be best to get the totals directly in the web view while rendering the status page. If we go this route we wouldn't be able to keep time-series data about it though. I'm not sure this stat would need timeseries since the only time it should be an issue is if the agent is offline for some reason and the queue builds up- the users should already be aware of agent problems via the status page.

**Comment by colsond** [comment]
From what I'm reading about pika there is no simple way to get the current queue count. The solution would be to use the system command and parse the output for queue names matching the csv2 groups. However, to run the rabbitmqctl system command one needs to be root or have explicit privileges. Perhaps this is a feature we can revisit after we've looked at signaling and locking down permissions & authentication for the rabbitmq server.

**Comment by rseuster** [comment]
added to epic ticket
