### ISSUE TITLE
web gui deletes when more than one security group used

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#259]
For e.g. dair-ab, we want to use two security groups: default and HTCondorWorker.

This can only be configured using the commandline:
```
$ cloudscheduler cloud update -cn dair-ab -vsg HTCondorWorker,default
cloud "testing::dair-ab" successfully updated.
```
After this all is fine:
```
$ cloudscheduler cloud list -V vm_security_groups
Server: dev2, Active User: seuster, Active Group: testing, User's Groups: ['test', 'test-dev2', 'testing']

Clouds:
+---------+---------+------------------------+
+         |         |     Cloud Default      +
+  Group  |  Cloud  |    Security Groups     +
+---------+---------+------------------------+
| testing | dair-ab | HTCondorWorker,default |
| testing | dair-qc | HTCondorWorker         |
| testing | otter   | default                |
+---------+---------+------------------------+
Rows: 3
```

Now, go to the webpage and update *something else* on the cloud, e.g. the spot market price,
which I changed from -1.0 to -1.4. After this the security groups are gone:
```
$ cloudscheduler cloud list -V vm_security_groups
Server: dev2, Active User: seuster, Active Group: testing, User's Groups: ['test', 'test-dev2', 'testing']

Clouds:
+---------+---------+-----------------+
+         |         |  Cloud Default  +
+  Group  |  Cloud  | Security Groups +
+---------+---------+-----------------+
| testing | dair-ab |                 |
| testing | dair-qc | HTCondorWorker  |
| testing | otter   | default         |
+---------+---------+-----------------+
Rows: 3
```

**Comment by colsond** [comment]
This looks like it stems from a flaw in the web ui. The list is created from querying the security groups table and since the new default that was created from the CLI doesn't string match any in the list the web display defaults to the empty option.

We need to upgrade the ui element to allow multiple selections which should fix this problem as it will have to process the current default.

A short term solution would be to add the default to the list of security groups if it isn't present.

________________________________

**Comment by rseuster** [comment]
fixed,closing
