### ISSUE TITLE
shortfall doesn't take into account how many of the needed resources need to be in the same VM

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#260]
initial situation:
- large number of idle multi-core jobs
- from time to time a single 1-core job in the queue
- flavor with single core and small number of RAM predefined for the enabled cloud

issue:
- csv2 boots as many VMs possible with the predefined 1core flavor, althought only 1 VM would be needed since the other jobs can't run in a VM with the predefined flavor
   - limited only by the amount of max booting VMs at the same time

The number of needed VMs depending on idle jobs and booted VM seems to take only into account the sum of CPU/DISK/RAM over all idle jobs but doesn't take into account how many of those resources need to be grouped in the same VM. 
From csmain:
```
vm_cpu_total = shortfall[0].shortfall_cores / cloud_match.flavor_cores
vm_disk_total = shortfall[0].shortfall_disk / cloud_match.flavor_disk if cloud_match.flavor_disk else None
vm_ram_total = shortfall[0].shortfall_ram / cloud_match.flavor_ram
```
which uses the same shortfall numbers for all flavors. In this case especially for a single core flavor although nearly all jobs need to have more than 1 core.

**Comment by colsond** [comment]
To expand on this a little more this was a result of investigating why none of the 2+ core jobs were running on dev2. We stepped through a boot cycle in csmain looking at the associated views.

The cycle starts by getting the list of "groups_of_idle_jobs" (which at the moment I don't quite understand how they are grouped). Then looping over this list it checks if there are any jobs from the grouping that are still idle and if so proceeds with the booting logic.

First it isolates the list of flavours defined in the flavour column of view_groups_of_idle_jobs. With this list of flavours it retrieves matching rows from view_available_resources to get a list of clouds from this group that have available resources. However, before doing anything with this list of clouds it retrieves the resource shortfalls from view_active_resources_shortfall which contains the shortfall of ALL the jobs in this grouping (in this case 1,2,3, and 4 core jobs). This is where we get to the block of code marcus mentioned above where the number of vms able to be booted is determined. Since the logic doesn't separately account for the 1, 2, 3, and 4 core jobs in this grouping it will try to boot the max allowable number of 1 core vms (provided there are enough resources) even if there is only a single 1 core job in this grouping of jobs.

The result is that cloudscheduler will always try to boot the max amount of VMs of the first flavour it inspects for a group of jobs provided there is ample resources available. Long term this would likely result in the bigger VM types being booted less and multi core jobs essentially having less(or no) vms available to run on.

On dev2 when a new batch of jobs come in they are a mix of 1-4 core jobs. Since the default flavour on otter was set to a single core flavour it always tried to boot 5 single core VMS even though there was only 1 single core job. This resulted in a lot of vms just getting cycled.


As to what a solution looks like I need to first understand how jobs are grouped- perhaps they should be grouped by the number of cores requested and then this issue would go away. Alternatively we need to find a way to let main know how many jobs can actually run on the vm flavoor it is trying to boot and limit the number of vms accordingly.

**Comment by rseuster** [comment]
is it fixed ?

**Comment by rseuster** [comment]
closing
