### ISSUE TITLE
amazon scheduling not working correctly

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#264]
On csv2a (stable-2.6.0+2commits):

When Amazon starts VMs using the spot market price, they go through the following cycle:
- starting
- unregistered
- Retiring
- Foreign

However, they are customized correctly and at one point show up in the Slot cores for busy/idle and run jobs. But they stay as foreign VMs and are therefore out of cloudscheduler's control.
In addition, the core quota (set for softmax as well as cores limit) is not observed and cloudscheduler starts more VMs when the previously started ones go into the foreign state. 

This seems to happen only when using the spot market pricing.

**Comment by colsond** [comment]
This issue was pretty far reaching and I've identified and fixed a few issues but there is still an outstanding problem with spot-price amazon VMS. For some reason when main tries to add the vm to our database sqlalchemy returns a primary key integrity error. The cause of this seems to be because the hostname is empty, but since a spot instance request doesn't get a hostname until it has booted there isn't much to be done in main.

I'm trying to figure out where in our database this stems from as the hostname is not part of the primary key for csv2_vms. I didn't think views had primary keys so perhaps it is the result of a trigger? Not sure how to proceed with this issue so any ideas would be beneficial.
