### ISSUE TITLE
Boot volumes should be deleted when instances are terminated

### ISSUE THREAD

**Issue by berghaus** [hep-gc/cloudscheduler#269]
When running on a cloud that requires the creation of a volume for the instances (e.g. LRZ) the boot volume needs to be deleted when the instance is terminated. The OpenStack API allows this to be set by putting `"shutdown": "remove"` in the block device mapping dictionary used when creating the instance.

**Comment by rseuster** [comment]
should be in, but it might not work in all cases.

**Comment by colsond** [comment]
I think this is something that has changed since the first version. It appears that block devices are now removed when their vm is terminated by default. In v1 there was an optional delete_on_termination flag that doesn't seem to exist in v2.
https://docs.openstack.org/nova/latest/user/block-device-mapping.html
