### ISSUE TITLE
mapping of VM states

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#277]
Currently,  VM states that are in CSV2 web display are:
Starting, Unreg., Idle, Running, Retiring, Manual, and Error

While the first 6 states are showing VMs which are in this state, VMs listed in the "Error" state are not only VMs that showed errors. Instead, all VMs that are not fitting in one of the previous categories are matched to "Error". This is very confusing since it is not clear if a real error occurred or in which state those machines are.   

It could be less confusing if the "Error" state is only used for VMs that show a real error, and a new state "Other" which collects all other VM states like terminating, shut-down,....

**Comment by colsond** [comment]
Initially these were mappings of openstack VM states that were then leveraged in a few different places for classification. The numbers showing on the web display are from view_cloud_status which sums up the totals using "poller_status" which is calculated in view_idle_vms. view_idle_vms sorts the vms into the following buckets using csv2_vms.status and the slot counts: "retiring", "starting", "unregistered", "idle", "running", and "error".

Now for amazon csv2 maps the VM states using the table ec2_instance_status_codes which currently only map to ACTIVE and ERROR (2 of the openstack states).

So in the end to make this change we need to explicitly redefine our states in view_idle_vms and perhaps add more states for amazon to map to since the current mapping looks like:
open/pending/running = ACTIVE
shutting-down/stopped/stopping/terminated = ERROR

**Comment by MarcusEbert** [comment]
How does it affect Openstack VMs that are shutdown - will they show up in error state or nowhere currently?

**Comment by colsond** [comment]
Since we destroy machines and never shut them down for csv2 i'd wager they'd show up as error state (although im not 100% sure I'm not sure we've ever had a machine in shutdown state), which seems appropriate for csv2 since if a machine is shut down it's certainly not running jobs.

**Comment by MarcusEbert** [comment]
It happened that machines end up in shutdown state when cs tried to terminate it.  
All VMs that are shown in error state are removed automatically after a certain time?

**Comment by colsond** [comment]
It should be marked for termination and removed after some time yes.

**Comment by rseuster** [comment]
guess we can close this one.
