### ISSUE TITLE
EPIC ticket: Plans and ideas for CSV2

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#295]
* display logfiles on web page (for remote users w/o account on machine)
https://github.com/hep-gc/cloudscheduler/issues/208
   * ability to rename metadata
https://github.com/hep-gc/cloudscheduler/issues/213
   * sort order in web display (could be anything, flavour, images and VM)
https://github.com/hep-gc/cloudscheduler/issues/216
   * use timeseries DB for web
https://github.com/hep-gc/cloudscheduler/issues/223
   * killing or retiring VMs should trigger openstack poller (otherwise can take 30seconds to show on web)
https://github.com/hep-gc/cloudscheduler/issues/234
   * "save plot" butting for web display
https://github.com/hep-gc/cloudscheduler/issues/239
   * show rabbitmq message queue depth in one of the detailed views
https://github.com/hep-gc/cloudscheduler/issues/251
   * glint: preselect image type based on ending
https://github.com/hep-gc/cloudscheduler/issues/255
   * naming conventions - add unit tests to create groups, clouds and target_alias
https://github.com/hep-gc/cloudscheduler/issues/270

plan for 2.7.1:
- openstack volume tracking #293 
- remove sqalchemy

**Comment by colsond** [comment]
> 
> 
>     * display logfiles on web page (for remote users w/o account on machine)
>       [Add new page to display log files #208](https://github.com/hep-gc/cloudscheduler/issues/208)

There is not much value in this because if you can't access the machine you won't be able to make changes anyways. There may be some value in being able to change csv2 configuration to fix issues manifesting in the logs. This will be very low priority.
> 
>     * ability to rename metadata
>       [rename metadata name #213](https://github.com/hep-gc/cloudscheduler/issues/213)
> 
Reasonable request- added to roadmap

>     * sort order in web display (could be anything, flavour, images and VM)
>       [have list items shown in alphabetical  order #216](https://github.com/hep-gc/cloudscheduler/issues/216)
> 
Sorting has already been added, functionality to be updated with vm-overlay audit

>     * use timeseries DB for web
>       [Use timeseries database for status page data #223](https://github.com/hep-gc/cloudscheduler/issues/223)
> 
mysql performance has increased enough to where this is not a major isssue, may be revisited if we peruse a public status page
 
>     * killing or retiring VMs should trigger openstack poller (otherwise can take 30seconds to show on web)
>       [killing or retiring VMs should trigger openstack poller #234](https://github.com/hep-gc/cloudscheduler/issues/234)
> 
Added to roadmap - need to issue signal from kill_retire function in view_utils
>     * "save plot" butting for web display
>       ["save plot" button for time series #239](https://github.com/hep-gc/cloudscheduler/issues/239)
> 
Added to roadmap - May be slated with other plotting upgrades

>     * show rabbitmq message queue depth in one of the detailed views
>       [show rabbitmq message queue depth in one of the detailed views #251](https://github.com/hep-gc/cloudscheduler/issues/251)
> 
No longer required- architecture change with remote condor pollers no longer relies on rabbitmq messages, rabbitmq now is only used for signals.
>     * glint: preselect image type based on ending
>       [glint: preselect image type based on ending #255](https://github.com/hep-gc/cloudscheduler/issues/255)
> 
Nice to have feature, very low priority
>     * naming conventions - add unit tests to create groups, clouds and target_alias
>       [allow capitalized letters as target_alias #270](https://github.com/hep-gc/cloudscheduler/issues/270)
> 
Unit tests and web tests to be merged.
> 
> plan for 2.7.1:
> 
>     * openstack volume tracking [csv2 should keep track of volumes and delete occasionally (specific for LRZ) #293](https://github.com/hep-gc/cloudscheduler/issues/293)
> 
>     * remove sqalchemy
Both done as of 2.9.0
