### ISSUE TITLE
Configuration file separation.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloudscheduler#3]
Configuration files for cloudscheduler and and other commands (cloud_admin, cloud_status, etc.) should be separate. Other recommendations for configuration file:

- YAML
- Resources per project.
- Server configs should be readable by admin/cloudscheduler only.

**Comment by colsond** [comment]
It should be noted that csv2 now has a table for storing yaml configuration (csv2_config) for the various csv2 components. Any config parsers that will be part of csv2 should get the majority of their configuration directly from a yaml dump in the database. However- since database connection parameters are required some local configuration will always be needed with the current setup.

**Comment by crlb** [comment]
DB config now only in /etc/cloudscheduler/cloudscheduler.yaml.
