### ISSUE TITLE
csv2 should print warning if I use a deleted cloud

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#36]
I submitted job to the old cloud "ccwesta", which I deleted earlier. csv2 should clearly reject jobs if they are asking for a cloud that doesn't exist.

from the logfile I only see this:
May 28 11:11:28 csv2 csv2: 2018-05-28 11:11:28,119:DEBUG:__main__:Info for current job: Group: atlas, Target: ccwesta, User: seuster@csv2.heprc.uvic.ca, Flavors: atlas:chameleon:m1.tiny

**Comment by mhpx** [comment]
Should the job the held as well or is just a warning in the log enough?

**Comment by rseuster** [comment]
I think, holding the job with a meaningful message would be the most useful.

**Comment by mhpx** [comment]
@crlb  In order to hold the jobs I'll need the IDs. view_groups_of_idle_jobs doesn't have the IDs, and view_condor_jobs_defaults_applied contains all the jobs separately. 

I need a way to unravel what view_groups_of_idle_jobs is giving me to get the job ids, or if that view could contain a list or range of the job_ids I can use?

**Comment by rseuster** [comment]
job should halt

**Comment by mhpx** [comment]
This may be more appropriate to put into the job poller at this stage. provided the poller is aware of which clouds are enabled or not.

**Comment by colsond** [comment]
If a cloud is deleted the jobs will be ignored as foreign jobs- we have code to hold these jobs but it has never been enabled (since we had more than one csv2 pointing at our condors we didn't want to hold eachothers jobs) and will now need to be updated to use the condor RPC client to perform the holds(if we want to hold foreign jobs).

The job poller doesn't really have a concept of cloud right now since it doesn't really matter which cloud the job runs on (unless set explicitly with target cloud or alias). Should a job be considered invalid if it's target cloud is disabled?


The other pollers will poll data from the cloud regardless of whether not they are enabled so we can be sure we aren't still running vms there.

**Comment by MarcusEbert** [comment]
We can discuss this in the next meeting, but I don't think we should do anything with foreign jobs at all. It may work for our scenarios to hold foreign jobs when we assume all jobs in condor are for that specific cloudscheduler only, but it would make cloudscheduler useless for other people, for example in the following scenarios:
- a group has a bare metal condor system and wants to extend it unused (opportunistic) cloud resources
- an HTCondor installation is used for different groups while only one of the groups has cloud resources available that are managed by cloudscheduler

In my opinion, things that are foreign are foreign for a a reason and should not be touched by cloudscheduler.

**Comment by rseuster** [comment]
admin to decide if jobs are to be held by csv2 or not. Need a config item for this, and then implementation.
jobs not having any csv2 variables (e.g. group set, then csv2 should not touch job.

**Comment by rseuster** [comment]
closing
