### ISSUE TITLE
Changing group after Cloud/Alias update causes additional update request to be sent

### ISSUE THREAD

**Issue by HeroHFM** [hep-gc/cloudscheduler#382]
On pages such as "Clouds" and "Aliases," submitting the form using the "Update" button changes the page URL from `list` to `update`. Next, if the group is changed with the drop down list on the top left, the page is reloaded with the new group which sends another update request via GET. Since the views are set up to reject GET requests, this produces an error. However, changing the group should probably not result in an additional update request.

Potential fixes could be to change the way the update views handle GET requests (for example the Group Defaults page uses the same view for handling POST and GET requests so it doesn't experience this issue), or changing how the group selector list reloads the page.

**Comment by colsond** [comment]
One possible solution is to redirect the page after a few seconds when the message///error message is cleared.

**Comment by colsond** [comment]
After looking into this a bit more we should look at using django's redirect response when returning from an update. Instead of rendering the group or cloud page as a response to a form submission what it does will instead tell the browser to redirect to a new url:
https://docs.djangoproject.com/en/4.1/topics/http/shortcuts/#redirect

The main issue that would arise from this change in response is how we handle error or success feedback messages. You can pass parameters with the redirect so it should all be pretty simple to hook up this way but it will take an overhaul of the messaging passed thru our python views.
