### ISSUE TITLE
image replication

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#50]
Since glint is integrated into cloudscheduler-2, it would be good to have:
- in the group defaults a default image defined that is used on all clouds if nothing is defined in the cloud specific part for that group
- glint knowing about the default image and automatically distributing it to all Openstack clouds defined for that project, especially when  a new cloud is defined within a project

**Comment by colsond** [comment]
With commit 3c573dc1b, the regular glint functionality, including keys should be supported. We will need to update the config table using the recently committed csv2-dev2 schema to support glint services via the new Config class.

The image collection service is now its own process instead of running on one of the celery nodes making it easy add another subprocess there to complete this(image replication) functionality or implement it as part of the image collection cycle. Since glint is already using redis for key storage, it would make sense as its own process that could be notified and awoken via a web request (like when a new cloud is added, or the defaults have been updated).

**Comment by colsond** [comment]
This functionality is supported on dev branch as of commit a3d7338b23b35220b03af002596277c8363e24a2.
Before this issue is closed I would like to add a few more things:

1. A UI element to the image matrix indicating which image is the group default.
2. A function to notify the replication subprocess of a change to the defaults via redis

**Comment by colsond** [comment]
I got about 90% of the way thru implementing this feature for keypairs as well before i realized there is no group default for keypairs. Each cloud (group resource) has it's own keypair defined. I can still make the process ensure that the key is present on the cloud (ie transfer it from another) but it isn't really a "Default" since it is explicitly set for each resource.

As I said i can implement this functionality but I'm no longer convinced that it belongs in "default_replication" without first adding support for a groupwide default for the keypair.

**Comment by colsond** [comment]
done
