### ISSUE TITLE
automatically retire VMs when needed

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#80]
When changing the cores that are usable for VMs on  a cloud to a lower value than actually used by csv2, VMs do not get retired to stay within the new limit. One has to retire VMs manually. 

Request: Have csv2 automatically retire VMs to stay within the new quota as soon as possible.

**Comment by colsond** [comment]
Did we ever finish the discussion about this or define the functionality we wanted from disabling a cloud or reducing the core count?

**Comment by MarcusEbert** [comment]
For the reducing of the cores used, something should retire - otherwise it doesn't make sense to reduce the cores I think.
I think the only open issue is about the algorithm used to decide which VMs get retired. Maybe the ones which are shown as most idle in condor?

**Comment by colsond** [comment]
in progress

**Comment by colsond** [comment]
Going to backpack off this issue but I noticed that the machine poller is unable to to submit commands to machines registered to a remote condor. I couldnt find a way around in the htcondor python docs and I've already messaged the htcondor mailing list hoping for a solution.

The alternatives are to run a daemon on any machine hosting a condor instance (yuk) to run the commands, or set up a method for issuing commands to a remote condor instance via the command line over an ssh connection.

**Comment by colsond** [comment]
It turns out the reason that csv2 was unable to execute the retire commands on the remote condor machines is due to a configuration problem. The yaml specified in the configuration only contained the condor host relevant to the machine and thus for any remote machines (not registered to the condor where csv2 is running) csv2 was denied access.

Marcus and I manually edited the default.yaml.j2 as follows and csv2 was then able to retire remote machines successfully.

```
HOSTALLOW_WRITE = $(IP_ADDRESS), $(FULL_HOSTNAME), $(CONDOR_HOST), csv2.heprc.uvic.ca
ALLOW_WRITE = $(IP_ADDRESS), $(FULL_HOSTNAME), $(CONDOR_HOST), csv2.heprc.uvic.ca
ALLOW_ADMINISTRATOR = $(CONDOR_HOST), csv2.heprc.uvic.ca
HOSTALLOW_ADMINISTRATOR = $(CONDOR_HOST), csv2.heprc.uvic.ca
```

I think we should consider maintaining a local configuration item for the csv2 host, either dynamically set in the configuration object or simply set in the /etc/cloudscheduler.yaml so that it could be easily added as a variable to the default yaml.
