### ISSUE TITLE
web interface core summary wrong

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#87]
On the status page of a project the total cores calculation is wrong or at least confusing.

examples: 
cc-east-a (atlas project) : 184 busy cores, 160 native cores, 2 foreign cores -> 162 total cores which should be 186 total cores 

cc-east-b (belle project): 0 busy cores, 582 native cores, 186 foreign cores -> 768 total cores, but 582 is the quota received from the cloud so 768 is impossible, it should be 186 total cores

**Comment by MarcusEbert** [comment]
Any news on that?

**Comment by kcasteels** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  This is fixed in dev. We will merge to prod on Monday.                                                                                                                                                                                                                                                                                                                                                   From: notifications@github.comSent: November 2, 2018 14:42To: cloudscheduler@noreply.github.comReply to: reply@reply.github.comCc: kcasteels@gmail.com; assign@noreply.github.comSubject: Re: [hep-gc/cloudscheduler] web interface core summary wrong (#87)  Any news on that?

—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MarcusEbert** [comment]
After the merge of dev, the cores have now changed to the quota from the cloud.
It would be more useful to show the real used cores (==busy cores+foreign cores). Also, some clouds do not provide a quota, like amazon, but the how many cores are used on the cloud currently is always helpful.

**Comment by colsond** [comment]
lots of changes
