### ISSUE TITLE
view_cloud_status should only return enabled clouds

### ISSUE THREAD

**Issue by kcasteels** [hep-gc/cloudscheduler#89]
We should consider only including enabled clouds in view_cloud_status.

**Comment by rseuster** [comment]
Well, here's the problem:
because csv2 doesn't regard quota's I disabled chameleon (they complained to us)
Now, it completely disappeared from the dashboard. VMs are still running, I see them on the
openstack dashboard

**Comment by colsond** [comment]
almost there

**Comment by crlb** [comment]
I don't agree; view_cloud_status should return all clouds but the user/developer has the option to filter out disabled clouds with filter(enabled=0). We talked about an "expanded status" line that showed disabled clouds, eg. "Disabled:  chameleon(0), coca(6)", the number in brackets indicating the number of running VMs.

Rolf, please review and tell us what you want.

**Comment by MarcusEbert** [comment]
I would prefer to see all clouds, enabled and disabled, but the disabled be marked as disabled, e.g. having the whole line (name and numbers) in light grey instead of black.

**Comment by MarcusEbert** [comment]
On the old monitoring page, we do not get any history time line for disabled clouds or clouds that do not currently run a VM, because they do not show up on the monitoring page to click on the numbers.   

To be able to do so in the new monitoring once we have a history, it would be good to always show the disabled clouds to be able to click on the numbers to get the history.

**Comment by kcasteels** [comment]
This has been resolved. Clouds still show up on the status page if they are disabled but have VMs running. They are coloured and there is a message in the expanded row about the disabled status.
